// Generates every design artifact from design/tokens.ts. Never edit the outputs.
//   npm run design        # write
//   npm run design:check  # verify only, non-zero exit when stale
//
// This module is deliberately SIDE-EFFECT FREE: importing it must never touch the
// filesystem. The staleness test imports buildCss/OUTPUTS, and if importing also
// regenerated the artifacts the test could never fail — it would repair the very
// drift it exists to catch. scripts/design.mjs is the entrypoint that calls main().
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { light, dark, fonts, cssVar } from '../design/tokens.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BANNER = '/* GENERATED by scripts/build-design.mjs from design/tokens.ts — DO NOT EDIT */';

/** Every comparison and every write goes through this. .gitattributes pins the
 *  current outputs to eol=lf, but a future output at an unpinned path would
 *  otherwise reintroduce the CRLF-vs-LF false positive on Windows checkouts. */
const lf = (s) => s.replace(/\r\n/g, '\n');

const decls = (t) => Object.keys(t).map((k) => `  ${cssVar(k)}:${t[k]};`).join('\n');

export function buildCss() {
  return [
    BANNER,
    ':root{',
    `  --serif:${fonts.serif};`,
    `  --sans:${fonts.sans};`,
    `  --mono:${fonts.mono};`,
    '}',
    '.tm-profile{',
    decls(light),
    '}',
    ':root[data-theme="dark"] .tm-profile{',
    decls(dark),
    '}',
    '',
  ].join('\n');
}

/** Replace the body between two markers in a hand-written file.
 *
 *  Region outputs edit a file that is mostly hand-written prose, so both failure
 *  modes throw rather than guess: a missing FILE is never created, and missing or
 *  malformed MARKERS never fall back to appending or overwriting. Either fallback
 *  would silently destroy prose that is not reproducible from design/tokens.ts. */
export function replaceRegion(current, marker, body) {
  const start = `<!-- generated:${marker}:start -->`;
  const end = `<!-- generated:${marker}:end -->`;
  if (current == null) {
    throw new Error(
      `region "${marker}": target file does not exist. A region output edits a hand-written ` +
        `file in place and never creates one — restore the file, then re-run.`,
    );
  }
  const i = current.indexOf(start);
  const j = current.indexOf(end);
  if (i === -1 || j === -1 || j < i) {
    throw new Error(
      `region "${marker}": missing or malformed markers. Expected ${start} before ${end}. ` +
        `Refusing to write — a region output never appends to or overwrites hand-written prose.`,
    );
  }
  return `${current.slice(0, i + start.length)}\n${body}\n${current.slice(j)}`;
}

/**
 * An artifact this script owns.
 *
 * `render` receives the CURRENT file text (null when the file does not exist), so an
 * output can rewrite a *region* of a hand-written file instead of owning the whole
 * file. `region: true` marks those: the file must already exist and is never created.
 *
 * @typedef {object} Output
 * @property {string} path                                  repo-relative
 * @property {(current: string | null) => string} render
 * @property {boolean} [region]  patch-in-place; missing file or markers throw
 */

/** @type {Output[]} */
export const OUTPUTS = [
  { path: 'src/styles/generated/tokens.css', render: () => buildCss() },
];

export function main(args = process.argv.slice(2)) {
  const check = args.includes('--check');
  let stale = 0;
  let wrote = 0;

  for (const out of OUTPUTS) {
    const p = resolve(root, out.path);
    const current = existsSync(p) ? lf(readFileSync(p, 'utf8')) : null;

    // A region output patches a hand-written file. Creating it from scratch would
    // produce a file with the generated body and none of the prose.
    if (out.region && current === null) {
      throw new Error(
        `${out.path}: region output is missing its file. Region outputs edit a ` +
          `hand-written file in place and never create one.`,
      );
    }

    const content = lf(out.render(current));
    if (current === content) continue;

    stale++;
    if (check) {
      console.error(`stale: ${out.path} — run \`npm run design\``);
      continue;
    }
    // Only whole-file outputs can need a directory; region outputs never create
    // anything, and a repo-root path has nothing to create.
    if (!out.region && dirname(p) !== root) mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
    wrote++;
    console.log(`wrote ${out.path}`);
  }

  // Both modes end with a summary line so silence is never mistaken for success:
  // design:check gates deploys, and "produced no output" must not read as "passed".
  const n = OUTPUTS.length;
  if (check && stale) {
    console.error(`design: ${stale} of ${n} artifact(s) stale — run \`npm run design\``);
    process.exitCode = 1; // not process.exit(1): that can truncate buffered stderr on Windows
    return;
  }
  if (wrote) console.log(`design: wrote ${wrote} of ${n} artifact(s)`);
  else console.log(`design: ${n} artifact(s) up to date`);
}
