// Generates every design artifact from design/tokens.ts. Never edit the outputs.
//   npm run design        # write
//   npm run design:check  # verify only, non-zero exit when stale
//
// This module is deliberately SIDE-EFFECT FREE: importing it must never touch the
// filesystem. The staleness test imports buildCss/OUTPUTS, and if importing also
// regenerated the artifacts the test could never fail — it would repair the very
// drift it exists to catch. scripts/design.mjs is the entrypoint that calls main().
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { light, dark, card, rounded, space, type as typeScale, semantic, fonts, cssVar } from '../design/tokens.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BANNER = '/* GENERATED by scripts/build-design.mjs from design/tokens.ts — DO NOT EDIT */';
const DESIGN_BANNER = 'GENERATED from DESIGN.md.tmpl by npm run design — DO NOT EDIT';

/** Every comparison and every write goes through this. .gitattributes pins the
 *  current outputs to eol=lf, but a future output at an unpinned path would
 *  otherwise reintroduce the CRLF-vs-LF false positive on Windows checkouts. */
const lf = (s) => s.replace(/\r\n/g, '\n');

const decls = (t) => Object.keys(t).map((k) => `  ${cssVar(k)}:${t[k]};`).join('\n');

export function buildCss() {
  return [
    BANNER,
    ':root{',
    `  --serif:${fonts.serif};`,
    `  --sans:${fonts.sans};`,
    `  --mono:${fonts.mono};`,
    '}',
    '.tm-profile{',
    decls(light),
    '}',
    ':root[data-theme="dark"] .tm-profile{',
    decls(dark),
    '}',
    '',
  ].join('\n');
}

/** The JS mirror of the tokens, for renderers that cannot read CSS custom properties:
 *  the dancer-card canvas, the OG images, and the injected map scripts.
 *
 *  `elev` is deliberately OMITTED from both `light` and `dark`. `light.elev` embeds
 *  `var(--tm-hi)`, a custom-property reference that resolves to nothing outside a
 *  stylesheet — genuinely unusable to this file's audience, so emitting it verbatim would
 *  ship a broken value and even a warning comment would still let a consumer read garbage.
 *  `dark.elev` is a fully resolvable box-shadow, but it is dropped too so the two themes
 *  keep an identical key set and any accidental `.elev` read fails at `tsc` instead of at
 *  paint time. This is NOT a claim that these renderers cannot draw shadows — Satori does
 *  render `box-shadow`, and app/u/[handle]/card/opengraph-image.tsx already paints one. A
 *  renderer that needs elevation should compose it from these tokens, not read `elev`. */
export function buildTs() {
  const lit = (o) => JSON.stringify(o, null, 2);
  const withoutElev = ({ elev, ...rest }) => rest;
  return [
    '// GENERATED by scripts/build-design.mjs from design/tokens.ts — DO NOT EDIT',
    '// Raw values for renderers that cannot read CSS custom properties: the card',
    '// canvas, the OG images, and the injected map scripts.',
    '// `elev` is intentionally omitted — it is a CSS box-shadow and light.elev embeds',
    '// var(--tm-hi), which no canvas/OG consumer can resolve. See scripts/build-design.mjs.',
    `export const light = ${lit(withoutElev(light))} as const;`,
    `export const dark = ${lit(withoutElev(dark))} as const;`,
    `export const card = ${lit(card)} as const;`,
    `export const rounded = ${lit(rounded)} as const;`,
    '',
  ].join('\n');
}

/** DESIGN.md is a GENERATED file: the prose lives in the hand-written DESIGN.md.tmpl,
 *  the VALUES come from design/tokens.ts. This substitutes every `{group.key}` placeholder
 *  in the template and returns the finished doc with a DO-NOT-EDIT banner. The banner is a
 *  YAML comment on line 2 (not an HTML comment on line 1) so the opening `---` stays first
 *  and the front matter still parses for gray-matter / remark-frontmatter / Astro / Jekyll.
 *
 *  Completeness is proven, not assumed: after substitution any surviving `{x.y}` throws,
 *  so the doc can never ship a literal placeholder. `{colors.X}` resolves through the
 *  `semantic` map to the LIGHT token value; the dark values appear only in `{tables.colors}`,
 *  the block that expands into the full light/dark colour table. An unknown key inside a
 *  known group (`{colors.bogus}`) throws immediately with the offender named; an unknown
 *  group (`{nope.x}`) is left untouched and caught by the survivor check below.
 *
 *  The template is LF-normalised first so the output is LF regardless of how the .tmpl is
 *  checked out — the staleness test compares render() output directly, byte for byte. */
export function buildDesign(tmpl) {
  const src = tmpl.replace(/\r\n/g, '\n');

  const colorTable = () => {
    const rows = Object.keys(semantic).map(
      (name) => `| ${name} | \`${light[semantic[name]]}\` | \`${dark[semantic[name]]}\` |`,
    );
    return ['| Token | Light | Dark |', '|---|---|---|', ...rows].join('\n');
  };

  const need = (group, key, table) => {
    if (!Object.prototype.hasOwnProperty.call(table, key)) {
      throw new Error(
        `DESIGN.md.tmpl: unknown placeholder {${group}.${key}} — "${key}" is not a key of \`${group}\` in design/tokens.ts.`,
      );
    }
    return table[key];
  };

  const groups = {
    colors: (key) => {
      if (!Object.prototype.hasOwnProperty.call(semantic, key)) {
        throw new Error(
          `DESIGN.md.tmpl: unknown placeholder {colors.${key}} — "${key}" is not in the \`semantic\` colour map in design/tokens.ts.`,
        );
      }
      return light[semantic[key]];
    },
    rounded: (key) => need('rounded', key, rounded),
    spacing: (key) => need('spacing', key, space),
    typography: (key) => need('typography', key, typeScale),
    tables: (key) => {
      if (key !== 'colors') {
        throw new Error(`DESIGN.md.tmpl: unknown placeholder {tables.${key}} — the only supported table is {tables.colors}.`);
      }
      return colorTable();
    },
  };

  // Strip the template's own editorial note (a leading HTML comment) so it is not carried
  // into DESIGN.md, which gets its own DO-NOT-EDIT banner instead.
  const withoutLeadNote = src.replace(/^(?:<!--[^]*?-->[ \t]*\n)+/, '');

  const PLACEHOLDER = /\{([a-z]+)\.([a-zA-Z0-9]+)\}/g;
  const body = withoutLeadNote.replace(PLACEHOLDER, (whole, group, key) =>
    Object.prototype.hasOwnProperty.call(groups, group) ? groups[group](key) : whole,
  );

  // The banner must not push the opening `---` off line 1, or every front-matter parser
  // (gray-matter, remark-frontmatter, Astro, Jekyll) stops recognising the header. So when
  // the template opens with YAML front matter, the banner rides in as a YAML comment on the
  // line right after the opening `---`; otherwise it prepends as an HTML comment.
  const out = body.startsWith('---\n')
    ? `---\n# ${DESIGN_BANNER}\n${body.slice('---\n'.length)}`
    : `<!-- ${DESIGN_BANNER} -->\n${body}`;

  // Loose on purpose. The substitution pass only recognises strict {lowercase.alnum}
  // tokens, so a near-miss — {Colors.primary} (case), {spacing.page-padding} (hyphen),
  // {rounded.md_2} (underscore) — is neither substituted nor caught by that grammar and
  // would ship literally. Catch ANY leftover brace-token instead. This assumes token VALUES
  // never contain {group.key}-shaped text, which holds because every CSS value the tokens
  // carry uses parentheses (rgba(), clamp(), var()), never braces.
  const survived = out.match(/\{[A-Za-z][\w.-]*\}/g);
  if (survived) {
    throw new Error(
      `DESIGN.md.tmpl: ${survived.length} brace-token(s) survived substitution — ` +
        `${[...new Set(survived)].join(', ')}. A generated doc must never ship a literal ` +
        `{x.y}; only {lowercase.alnum} is substituted, so fix the typo, add a resolver, or ` +
        `remove the placeholder from the template.`,
    );
  }
  return out;
}

/** Reads the hand-written DESIGN.md template, failing with a guided message — like the
 *  region and whole-file guards — instead of a raw ENOENT stack trace when it has been
 *  deleted. DESIGN.md is generated FROM this file, so it cannot be reconstructed without it. */
function readDesignTemplate() {
  const p = resolve(root, 'DESIGN.md.tmpl');
  if (!existsSync(p)) {
    throw new Error(
      `DESIGN.md.tmpl is missing — DESIGN.md is generated from it, not hand-edited. ` +
        `Restore it (git checkout -- DESIGN.md.tmpl), then re-run \`npm run design\`.`,
    );
  }
  return readFileSync(p, 'utf8');
}

const count = (haystack, needle) => haystack.split(needle).length - 1;

/** Replace the body between two markers in a hand-written file.
 *
 *  Region outputs edit a file that is mostly hand-written prose, so every ambiguity
 *  throws rather than guessing: a missing FILE is never created, and absent, inverted
 *  or DUPLICATED markers never fall back to appending or overwriting. Any of those
 *  would silently destroy prose that is not reproducible from design/tokens.ts.
 *
 *  Duplicates matter more than they look: the target is a document *about* the design
 *  system, so a maintainer mentioning the marker convention in prose — or showing it
 *  in a fenced example — is the expected case, not a freak one. indexOf would then
 *  splice from their mention to the real region and delete everything between. */
export function replaceRegion(current, marker, body) {
  const start = `<!-- generated:${marker}:start -->`;
  const end = `<!-- generated:${marker}:end -->`;
  if (current == null) {
    throw new Error(
      `region "${marker}": target file does not exist. A region output edits a hand-written ` +
        `file in place and never creates one — restore the file, then re-run.`,
    );
  }
  const i = current.indexOf(start);
  const j = current.indexOf(end);
  if (i === -1 || j === -1) {
    throw new Error(
      `region "${marker}": missing or malformed markers. Expected ${start} before ${end}. ` +
        `Refusing to write — a region output never appends to or overwrites hand-written prose.`,
    );
  }
  const starts = count(current, start);
  const ends = count(current, end);
  if (starts !== 1 || ends !== 1) {
    throw new Error(
      `region "${marker}": expected exactly one ${start} and one ${end}, found ${starts} and ` +
        `${ends}. Refusing to write — an ambiguous marker pair would splice generated output ` +
        `into hand-written prose.`,
    );
  }
  if (j < i) {
    throw new Error(
      `region "${marker}": missing or malformed markers. Expected ${start} before ${end}. ` +
        `Refusing to write — a region output never appends to or overwrites hand-written prose.`,
    );
  }
  return `${current.slice(0, i + start.length)}\n${body}\n${current.slice(j)}`;
}

/**
 * An artifact this script owns.
 *
 * `render` receives the CURRENT file text (null when the file does not exist), so an
 * output can rewrite a *region* of a hand-written file instead of owning the whole
 * file. `region: true` marks those: the file must already exist and is never created.
 *
 * @typedef {object} Output
 * @property {string} path                                  repo-relative
 * @property {(current: string | null) => string} render
 * @property {boolean} [region]  patch-in-place; missing file or markers throw
 */

/** @type {Output[]} */
export const OUTPUTS = [
  { path: 'src/styles/generated/tokens.css', render: () => buildCss() },
  { path: 'src/lib/generated/tokens.ts', render: () => buildTs() },
  // Whole-file generated output (not a region patch): render reads the hand-written
  // TEMPLATE, not the current DESIGN.md, and substitutes token values into it.
  { path: 'DESIGN.md', render: () => buildDesign(readDesignTemplate()) },
];

export function main(args = process.argv.slice(2)) {
  const check = args.includes('--check');
  let stale = 0;
  let wrote = 0;

  for (const out of OUTPUTS) {
    const p = resolve(root, out.path);
    const current = existsSync(p) ? lf(readFileSync(p, 'utf8')) : null;

    // A region output patches a hand-written file. Creating it from scratch would
    // produce a file with the generated body and none of the prose.
    if (out.region && current === null) {
      throw new Error(
        `${out.path}: region output is missing its file. Region outputs edit a ` +
          `hand-written file in place and never create one.`,
      );
    }

    const content = lf(out.render(current));
    if (current === content) continue;

    stale++;
    if (check) {
      console.error(`stale: ${out.path} — run \`npm run design\``);
      continue;
    }
    // Only whole-file outputs can need a directory; region outputs never create
    // anything, and a repo-root path has nothing to create.
    if (!out.region && dirname(p) !== root) mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
    wrote++;
    console.log(`wrote ${out.path}`);
  }

  // Both modes end with a summary line so silence is never mistaken for success:
  // design:check gates deploys, and "produced no output" must not read as "passed".
  const n = OUTPUTS.length;
  if (check && stale) {
    console.error(`design: ${stale} of ${n} artifact(s) stale — run \`npm run design\``);
    process.exitCode = 1; // not process.exit(1): that can truncate buffered stderr on Windows
    return;
  }
  if (wrote) console.log(`design: wrote ${wrote} of ${n} artifact(s)`);
  else console.log(`design: ${n} artifact(s) up to date`);
}
