// Generates every design artifact from design/tokens.ts. Never edit the outputs.
//   npm run design        # write
//   npm run design:check  # verify only, non-zero exit when stale
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { light, dark, fonts, cssVar } from '../design/tokens.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BANNER = '/* GENERATED by scripts/build-design.mjs from design/tokens.ts — DO NOT EDIT */';

const decls = (t) => Object.keys(t).map((k) => `  ${cssVar(k)}:${t[k]};`).join('\n');

export function buildCss() {
  return [
    BANNER,
    ':root{',
    `  --serif:${fonts.serif};`,
    `  --sans:${fonts.sans};`,
    `  --mono:${fonts.mono};`,
    '}',
    '.tm-profile{',
    decls(light),
    '}',
    ':root[data-theme="dark"] .tm-profile{',
    decls(dark),
    '}',
    '',
  ].join('\n');
}

const OUTPUTS = () => [['src/styles/generated/tokens.css', buildCss()]];

function main() {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [rel, content] of OUTPUTS()) {
    const p = resolve(root, rel);
    const current = existsSync(p) ? readFileSync(p, 'utf8') : null;
    if (current === content) continue;
    stale++;
    if (check) { console.error(`stale: ${rel}`); continue; }
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
    console.log(`wrote ${rel}`);
  }
  if (check && stale) process.exit(1);
  if (!check && !stale) console.log('all design artifacts already up to date');
}

// Only generate when run as a script. The staleness test imports buildCss, and if
// importing also rewrote the artifact the test could never fail — it would repair
// the very drift it exists to catch.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
