// Extracts the canonical 62-skill list from the map bundle into src/data/skills.ts.
// Run: node scripts/extract-skills.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const html = readFileSync('public/tangomap.html', 'utf8');
const open = '<script type="__bundler/template">';
const i = html.indexOf(open) + open.length;
const j = html.indexOf('</script>', i);
const tpl = JSON.parse(html.slice(i, j).trim());

// Node objects look like: id:'mirada-cabeceo', name:'Mirada & Cabeceo', level:0, tag:'PARTNER', ...
// Slice the template into per-node chunks (from each id:'...' to the next) so each node's
// own name/level/tag are read in isolation — robust to field order and escaped names.
const idRe = /id:'([a-z0-9-]+)'/g;
const marks = [];
let im;
while ((im = idRe.exec(tpl)) !== null) marks.push({ slug: im[1], at: im.index });

const seen = new Set();
const skills = [];
for (let k = 0; k < marks.length; k++) {
  const slug = marks[k].slug;
  if (seen.has(slug)) continue;
  const chunk = tpl.slice(marks[k].at, k + 1 < marks.length ? marks[k + 1].at : marks[k].at + 2000);
  // names may use ' or " delimiters (double-quoted when they contain an apostrophe).
  const nameM = chunk.match(/name:(['"])((?:\\.|(?!\1)[^\\])*)\1/);
  const levelM = chunk.match(/level:(\d+)/);
  const tagM = chunk.match(/tag:'([A-Z_ ]+)'/);
  if (!nameM || !levelM || !tagM) continue; // not a real skill node
  seen.add(slug);
  skills.push({
    slug,
    name: nameM[2].replace(/\\(['"\\])/g, '$1'),
    level: parseInt(levelM[1], 10) + 1, // bundle 0-indexed -> human 1..10
    tag: tagM[1],
  });
}

if (skills.length !== 62) throw new Error(`expected 62 skills, got ${skills.length}`);
const levels = new Set(skills.map((s) => s.level));
for (let l = 1; l <= 10; l++) if (!levels.has(l)) throw new Error(`missing level ${l}`);

const body = skills
  .map((s) => `  { slug: ${JSON.stringify(s.slug)}, name: ${JSON.stringify(s.name)}, level: ${s.level}, tag: ${JSON.stringify(s.tag)} },`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/extract-skills.mjs — do not edit by hand.
export type Skill = { slug: string; name: string; level: number; tag: string };

export const SKILLS: Skill[] = [
${body}
];

export const SKILL_SLUGS: Set<string> = new Set(SKILLS.map((s) => s.slug));
`;

mkdirSync('src/data', { recursive: true });
writeFileSync('src/data/skills.ts', out);
console.log(`OK: wrote src/data/skills.ts (${skills.length} skills, levels ${[...levels].sort((a, b) => a - b).join(',')})`);
