// Extracts the canonical 62-skill list from the map bundle into src/data/skills.ts.
// Run: node scripts/extract-skills.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const html = readFileSync('public/tangomap.html', 'utf8');
const open = '<script type="__bundler/template">';
const i = html.indexOf(open) + open.length;
const j = html.indexOf('</script>', i);
const tpl = JSON.parse(html.slice(i, j).trim());

// Node objects look like: id:'mirada-cabeceo', name:'Mirada & Cabeceo', level:0, tag:'PARTNER', ...
const re = /id:'([a-z0-9-]+)',\s*name:'((?:\\.|[^'\\])*)',\s*level:(\d+)/g;
const seen = new Set();
const skills = [];
let m;
while ((m = re.exec(tpl)) !== null) {
  const slug = m[1];
  if (seen.has(slug)) continue;
  seen.add(slug);
  const name = m[2].replace(/\\'/g, "'").replace(/\\\\/g, '\\');
  const level = parseInt(m[3], 10) + 1; // bundle is 0-indexed; expose human 1..10
  skills.push({ slug, name, level });
}

if (skills.length !== 62) throw new Error(`expected 62 skills, got ${skills.length}`);
const levels = new Set(skills.map((s) => s.level));
for (let l = 1; l <= 10; l++) if (!levels.has(l)) throw new Error(`missing level ${l}`);

const body = skills
  .map((s) => `  { slug: ${JSON.stringify(s.slug)}, name: ${JSON.stringify(s.name)}, level: ${s.level} },`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/extract-skills.mjs — do not edit by hand.
export type Skill = { slug: string; name: string; level: number };

export const SKILLS: Skill[] = [
${body}
];

export const SKILL_SLUGS: Set<string> = new Set(SKILLS.map((s) => s.slug));
`;

mkdirSync('src/data', { recursive: true });
writeFileSync('src/data/skills.ts', out);
console.log(`OK: wrote src/data/skills.ts (${skills.length} skills, levels ${[...levels].sort((a, b) => a - b).join(',')})`);
