// The app's SKILLS list — a projection of the authoritative map data in
// src/data/mapNodes.ts. Each skill is one map node with a 1-indexed level
// (the map data is 0-indexed; the app displays levels 1..10).
//
// NOTE: this file used to be generated by scripts/extract-skills.mjs from
// public/tangomap.html. It now derives from mapNodes.ts instead, so the map,
// the bundle, and the app all read from one source of truth.
import { MAP_NODES } from '@/src/data/mapNodes';

/** deps = prerequisite slugs (this skill's inbound edges in the map's graph). */
export type Skill = { slug: string; name: string; level: number; tag: string; deps: string[] };

export const SKILLS: Skill[] = MAP_NODES.map((n) => ({
  slug: n.id,
  name: n.name,
  level: n.level + 1, // map data is 0-indexed -> human 1..10
  tag: n.tag,
  deps: n.deps,
}));

export const SKILL_SLUGS: Set<string> = new Set(SKILLS.map((s) => s.slug));
